In [11]:
import numpy as np
import pandas as pd

In [2]:
vecotr_row = np.array([1, 2, 3])

In [6]:
vecotr_row

array([1, 2, 3])

In [9]:
vecotr_col = np.array([[1],
                       [2],
                       [3]])

In [10]:
vecotr_col 

array([[1],
       [2],
       [3]])

##  資料整理

In [13]:
url = 'https://tinyurl.com/titanic-csv'
dataframe = pd.read_csv(url)

In [22]:
dataframe.head(5) ## head -> 前五個

Name PClass    Age     Sex  \
0                   Allen, Miss Elisabeth Walton    1st  29.00  female   
1                    Allison, Miss Helen Loraine    1st   2.00  female   
2            Allison, Mr Hudson Joshua Creighton    1st  30.00    male   
3  Allison, Mrs Hudson JC (Bessie Waldo Daniels)    1st  25.00  female   
4                  Allison, Master Hudson Trevor    1st   0.92    male   

   Survived  SexCode  
0         1        1  
1         0        1  
2         0        0  
3         0        1  
4         1        0

In [56]:
np.zeros(2)

array([0., 0.])

In [26]:
dataframe.describe()

Age     Survived      SexCode
count  756.000000  1313.000000  1313.000000
mean    30.397989     0.342727     0.351866
std     14.259049     0.474802     0.477734
min      0.170000     0.000000     0.000000
25%     21.000000     0.000000     0.000000
50%     28.000000     0.000000     0.000000
75%     39.000000     1.000000     1.000000
max     71.000000     1.000000     1.000000

## linear regression

In [28]:
from sklearn.linear_model import LinearRegression
from sklearn.datasets import load_boston

In [32]:
boston = load_boston()
features = boston.data[:, 0:2]
target = boston.target

In [60]:
for x, y in zip(features, target):
    print(x, y)

[6.32e-03 1.80e+01] 24.0
[0.02731 0.     ] 21.6
[0.02729 0.     ] 34.7
[0.03237 0.     ] 33.4
[0.06905 0.     ] 36.2
[0.02985 0.     ] 28.7
[ 0.08829 12.5    ] 22.9
[ 0.14455 12.5    ] 27.1
[ 0.21124 12.5    ] 16.5
[ 0.17004 12.5    ] 18.9
[ 0.22489 12.5    ] 15.0
[ 0.11747 12.5    ] 18.9
[ 0.09378 12.5    ] 21.7
[0.62976 0.     ] 20.4
[0.63796 0.     ] 18.2
[0.62739 0.     ] 19.9
[1.05393 0.     ] 23.1
[0.7842 0.    ] 17.5
[0.80271 0.     ] 20.2
[0.7258 0.    ] 18.2
[1.25179 0.     ] 13.6
[0.85204 0.     ] 19.6
[1.23247 0.     ] 15.2
[0.98843 0.     ] 14.5
[0.75026 0.     ] 15.6
[0.84054 0.     ] 13.9
[0.67191 0.     ] 16.6
[0.95577 0.     ] 14.8
[0.77299 0.     ] 18.4
[1.00245 0.     ] 21.0
[1.13081 0.     ] 12.7
[1.35472 0.     ] 14.5
[1.38799 0.     ] 13.2
[1.15172 0.     ] 13.1
[1.61282 0.     ] 13.5
[0.06417 0.     ] 18.9
[0.09744 0.     ] 20.0
[0.08014 0.     ] 21.0
[0.17505 0.     ] 24.7
[2.763e-02 7.500e+01] 30.8
[3.359e-02 7.500e+01] 34.9
[0.12744 0.     ] 26.6
[0.1415 0.    

In [39]:
regression = LinearRegression()
model = regression.fit(features, target)

In [40]:
model.intercept_

22.485628113468223

In [42]:
model.coef_

array([-0.35207832,  0.11610909])

In [46]:
target[0]*1000

24000.0

In [50]:
model.predict(features)[0]*1000

24573.366631705547

In [51]:
model.coef_[0]*1000

-352.07831564026765