In [3]:
import numpy as np

## 隨機小陣列

In [4]:
data = np.random.randn(2,5)

In [5]:
data

array([[ 0.30667994, -0.18470612,  0.42713671, -1.54974982, -0.63090755],
       [-0.15383032,  1.57938657,  1.39984972, -1.05401309, -0.31284349]])

In [6]:
data * 10

array([[  3.0667994 ,  -1.8470612 ,   4.27136706, -15.49749819,
         -6.30907546],
       [ -1.53830317,  15.79386565,  13.99849723, -10.54013089,
         -3.12843494]])

In [7]:
data + data

array([[ 0.61335988, -0.36941224,  0.85427341, -3.09949964, -1.26181509],
       [-0.30766063,  3.15877313,  2.79969945, -2.10802618, -0.62568699]])

## 每個陣列都有 .shape .dtype

In [8]:
data.shape

(2, 5)

In [9]:
data.dtype

dtype('float64')

## 建立array

In [27]:
data1 = [5, 6, 7, 7, 8.9876] #list 適合傳入變陣列

In [28]:
arr1 = np.array(data1)

In [29]:
arr1

array([5.    , 6.    , 7.    , 7.    , 8.9876])

## 巢式list

In [38]:
data2 = [[1, 2, 3],
         [10, 20, 30.]] 

In [39]:
arr2 = np.array(data2)

In [40]:
arr2

array([[ 1.,  2.,  3.],
       [10., 20., 30.]])

In [43]:
arr2.ndim

2

In [44]:
arr2.shape 

(2, 3)

In [45]:
arr2.dtype

dtype('float64')

## zeros & ones & empty 

In [46]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [52]:
np.ones((2,3)) # NEED tuple

array([[1., 1., 1.],
       [1., 1., 1.]])

In [23]:
np.zeros((2,3,4,5)) ## 解讀由右而左 5 x 4 matrix x 3 x 2

array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]])

## np.arange() 

In [68]:
np.arange(10) # np 版 range

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## astype cast(轉換）dtype

In [65]:
arr2.dtype

dtype('float64')

In [71]:
arr3 = arr2.astype('int64')

In [73]:
arr4 = arr2.astype(np.int32)

In [63]:
arr3.dtype

dtype('int64')

In [74]:
arr4.dtype

dtype('int32')

## np 的 array 運算 

In [75]:
## same size 

In [79]:
arr = np.array([[1,2,3],[4,5,6]])

In [80]:
arr * arr

array([[ 1,  4,  9],
       [16, 25, 36]])

In [81]:
arr - arr

array([[0, 0, 0],
       [0, 0, 0]])

In [82]:
1/arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [83]:
arr ** 0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [84]:
arr2 = np.array([[3,2,2],[4,1,1]])

In [85]:
arr >= arr2

array([[False,  True,  True],
       [ True,  True,  True]])

## 索引 和 切片

In [96]:
arr = np.arange(10)

In [97]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [100]:
arr[5]# 跟list alike note: arr[5]其實是6th元素

5

In [102]:
arr[5:8] #6th~8th元素 尾數!!!

array([5, 6, 7])

## 修改值 

In [103]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [106]:
arr[1:4] = 99

In [107]:
arr

array([ 0, 99, 99, 99,  4,  5,  6,  7,  8,  9])

## 廣播是什麼？

In [109]:
arr = np.arange(10)

In [110]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [119]:
arr_slice = arr[1:4] 

In [120]:
arr_slice

array([1, 2, 3])

In [121]:
## change arr_slice
arr_slice[:] = 99

In [122]:
arr_slice

array([99, 99, 99])

In [124]:
arr
## 在arr_slice的修改也會影響到arr

array([ 0, 99, 99, 99,  4,  5,  6,  7,  8,  9])

## .copy()

In [131]:
arr = np.arange(10)

In [132]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [139]:
arr_slice = arr[1:4].copy()##複製出去，獨立的 

In [140]:
arr_slice

array([1, 2, 3])

In [141]:
## change arr_slice
arr_slice[:] = 99

In [142]:
arr_slice

array([99, 99, 99])

In [138]:
arr
## 在arr_slice的修改 不改變arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## 高維度 

In [5]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [6]:
arr2d.shape

(3, 3)

In [7]:
arr2d[2]

array([7, 8, 9])

In [8]:
arr2d[2,1]

8

In [9]:
arr2d[2][1] 

8

In [21]:
arr2d[:2, 1:]

array([[2, 3],
       [5, 6]])

## Bool index

In [12]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

In [13]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [6]:
data = np.random.randn(7,4)

In [7]:
data

array([[ 0.15557268,  0.82230048,  0.0407293 , -0.33282806],
       [-0.14062181, -0.34628415,  1.93674996,  1.23376281],
       [-2.25691586, -0.34142879,  0.15526402,  0.25034398],
       [ 0.47602706, -0.18558022,  0.18470654, -0.96540183],
       [-0.94374593,  0.61347927,  0.39872963,  2.73948624],
       [-2.46243816, -1.02886294,  0.59610283,  1.30105677],
       [ 0.14489706,  0.94406652, -0.99098484,  0.05512407]])

In [15]:
names == 'Bob'

array([ True, False, False,  True, False, False, False])

In [16]:
data[names == 'Bob']

array([[ 0.15557268,  0.82230048,  0.0407293 , -0.33282806],
       [ 0.47602706, -0.18558022,  0.18470654, -0.96540183]])

In [18]:
data[[0,3],:]

array([[ 0.15557268,  0.82230048,  0.0407293 , -0.33282806],
       [ 0.47602706, -0.18558022,  0.18470654, -0.96540183]])

In [28]:
data[names == 'Bob', 2:]

array([[ 0.0407293 , -0.33282806],
       [ 0.18470654, -0.96540183]])

In [25]:
data[names == 'Bob', 3]

array([-0.33282806, -0.96540183])