# 執行元素級別的運算 ufunc #一元

In [1]:
import numpy as np

In [2]:
arr = np.arange(10)

In [3]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [6]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

# 執行元素級別的運算 ufunc #二元

In [8]:
x = np.random.rand(8)

In [9]:
x

array([0.04559509, 0.97274686, 0.21090256, 0.06202459, 0.46380584,
       0.10194667, 0.28963059, 0.08418736])

In [10]:
y = np.random.rand(8)

In [11]:
y

array([0.88940701, 0.20715118, 0.61004195, 0.2257239 , 0.02386375,
       0.44306379, 0.4701816 , 0.41744433])

In [12]:
x + y 

array([0.9350021 , 1.17989804, 0.82094451, 0.28774849, 0.48766959,
       0.54501046, 0.75981218, 0.50163169])

In [15]:
np.maximum(x, y)

array([0.88940701, 0.97274686, 0.61004195, 0.2257239 , 0.46380584,
       0.44306379, 0.4701816 , 0.41744433])

In [16]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
arr = np.random.rand(7) * 5

In [18]:
arr

array([4.6447189 , 0.66647179, 2.84199227, 3.34198201, 1.99064002,
       4.62403252, 4.05789138])

In [19]:
remainder, whole_part = np.modf(arr)

In [20]:
remainder # 小數部分

array([0.6447189 , 0.66647179, 0.84199227, 0.34198201, 0.99064002,
       0.62403252, 0.05789138])

In [21]:
whole_part #整數

array([4., 0., 2., 3., 1., 4., 4.])